import type {
  SourceAdapter,
  RawIpoRecord,
  RawGmpRecord,
  RawSubscriptionRecord,
  RawArticleRecord,
  RawReviewRecord,
} from "@/types/ingestion";

/**
 * Placeholder adapter used until real API keys / scrapers are configured.
 * Every record is explicitly labelled with source = "Mock Data Source" so it
 * can never be mistaken for a live figure. Replace with a real adapter (see
 * adapters/README.md) before deploying to production — services/*.ts read
 * the DataSource table to decide which adapter(s) are active.
 */
export class MockSourceAdapter implements SourceAdapter {
  private readonly companies = [
    { name: "Solara Energy Systems", slug: "solara-energy-systems-ipo" },
    { name: "Vantic Pharma", slug: "vantic-pharma-ipo" },
    { name: "Northbridge Logistics", slug: "northbridge-logistics-ipo" },
    { name: "Kestrel Digital Payments", slug: "kestrel-digital-payments-ipo" },
  ];

  async fetchUpcomingIPOs(): Promise<RawIpoRecord[]> {
    const now = Date.now();
    const day = 86_400_000;
    return this.companies.map((c, i) => ({
      name: `${c.name} IPO`,
      slug: c.slug,
      company: `${c.name} Ltd`,
      type: "MAINBOARD",
      priceBandMin: 100 + i * 50,
      priceBandMax: 110 + i * 50,
      lotSize: 40,
      issueSizeCr: 500 + i * 200,
      openDate: new Date(now + i * day).toISOString(),
      closeDate: new Date(now + (i + 2) * day).toISOString(),
      allotmentDate: new Date(now + (i + 4) * day).toISOString(),
      listingDate: new Date(now + (i + 6) * day).toISOString(),
      registrar: "Kfin Technologies Ltd",
      registrarUrl: "https://kfintech.com",
      leadManagers: ["Mock Capital Advisors"],
      source: "Mock Data Source",
      sourceUrl: "https://example.com/mock-source",
    }));
  }

  async fetchGMP(): Promise<RawGmpRecord[]> {
    return this.companies.map((c) => ({
      ipoSlug: c.slug,
      gmp: Math.round((Math.random() - 0.3) * 200),
      source: "Mock Data Source",
    }));
  }

  async fetchSubscriptions(): Promise<RawSubscriptionRecord[]> {
    return this.companies.map((c, i) => ({
      ipoSlug: c.slug,
      day: 1,
      qib: Number((Math.random() * 5).toFixed(2)),
      nii: Number((Math.random() * 10).toFixed(2)),
      retail: Number((Math.random() * 6).toFixed(2)),
      total: Number((Math.random() * 8 + i).toFixed(2)),
      source: "Mock Data Source",
    }));
  }

  async fetchArticles(): Promise<RawArticleRecord[]> {
    return [
      {
        title: "Weekly IPO market wrap",
        slug: `weekly-ipo-market-wrap-${Date.now()}`,
        excerpt: "A summary of this week's primary market activity.",
        content: "Placeholder content generated by the mock adapter for local development.",
        category: "NEWS",
        source: "Mock Data Source",
        sourceUrl: "https://example.com/mock-source",
        publishedAt: new Date().toISOString(),
      },
    ];
  }

  async fetchReviews(): Promise<RawReviewRecord[]> {
    return this.companies.map((c) => ({
      ipoSlug: c.slug,
      sentiment: "NEUTRAL",
      positivePct: 40,
      neutralPct: 40,
      negativePct: 20,
      reviewCount: 50,
      source: "Mock Data Source",
      sourceUrl: "https://example.com/mock-source",
    }));
  }
}

export const mockSourceAdapter = new MockSourceAdapter();
